### ISSUE TITLE
Connector not working

### ISSUE THREAD

**Issue by lenilopes** [Hugoberry/FacebookAds#1]
Hello,
Thank you very much for this connector. I'm not able to load my ads account. 
I have this error : 

```
DataSource.Error : Web.Contents n'a pas réussi à obtenir le contenu de « https://graph.facebook.com/v2.11/act_10211012471928721/campaigns?access_token=EAAdAzsVjmowBAARjeJfVd1ZCOaJ5TN4YF0naAESUZBKkhet2Hq81LjZC0bkOpu8aAqF1zo2AjmI7ZCPoU48ZC2L7JyeHqDadblUHDrHP9xFFZCjixZCZANI2q55QRd16FZBAml9C983rIaJoC8EUSIyDSrOJ8bRStRw5ZBdIa1fZAPdvgZDZD&fields=name » (400) : Bad Request
Détails :
    DataSourceKind=FacebookAds
    DataSourcePath=FacebookAds
    Url=https://graph.facebook.com/v2.11/act_10211012471928721/campaigns?access_token=EAAdAzsVjmowBAARjeJfVd1ZCOaJ5TN4YF0naAESUZBKkhet2Hq81LjZC0bkOpu8aAqF1zo2AjmI7ZCPoU48ZC2L7JyeHqDadblUHDrHP9xFFZCjixZCZANI2q55QRd16FZBAml9C983rIaJoC8EUSIyDSrOJ8bRStRw5ZBdIa1fZAPdvgZDZD&fields=name
```
It's in french but it says Web.Contents failed to obtain the content of ....
Thank you for your help, I hope you will be able to solve this. It would be so great if the connector could work ! :D

**Comment by Hugoberry** [comment]
Hi Lionel,
It seems that you have authenticated through the API, however you don't have the capability to make Facebook API calls. Still investigating this. 
It appears that the user associated with the token is only having _analyst_ access to the account in Business Manager.  Is it possible to grant the user advertiser role?
https://stackoverflow.com/questions/40142294/facebook-ads-insights-api-3-application-does-not-have-the-capability-to-make/40159388

**Comment by Hugoberry** [comment]
Had another check. 
The Facebook app that I've created to be able to read Marketing API is in developer mode, and thus restricted to only 5 managed accounts. I will start the the upgrading process, but this might take a while as it all depends on FB review timelines. 
![image](https://user-images.githubusercontent.com/6012338/37699568-02cdf6e2-2ce0-11e8-98ba-3d9198cbac91.png)
